import { Bell, CheckCircle2, ChevronRight, ClipboardList, Clock3, Hospital, MapPinned, Plus, ShieldAlert, Siren, TriangleAlert } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import CitizenLayout from '../../components/citizen/CitizenLayout.jsx';
import { reportsApi } from '../../services/reportService.js';
import { emergencyApi, facilitiesApi, label } from '../../services/emergencyService.js';
import { notificationsApi } from '../../services/notificationService.js';
import { apiMessage } from '../../services/api.js';
import { SkeletonPage } from '../../components/ui/Skeleton.jsx';
import AIBriefingCard from '../../components/ai/AIBriefingCard.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import useEmergencyEvents from '../../hooks/useEmergencyEvents.js';

const activeReportStatuses = new Set(['pending', 'verified', 'assigned', 'in_progress', 'under_review']);
const activeEmergencyStatuses = new Set(['reported', 'received', 'assessing', 'verified', 'dispatched', 'en_route', 'on_scene', 'responding', 'requires_backup']);
const dateTime = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Recently updated';
const reportTone = (status) => status === 'completed' || status === 'closed' ? 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 ring-emerald-200' : status === 'in_progress' || status === 'assigned' ? 'bg-blue-50 dark:bg-blue-950/40 text-blue-700 dark:text-blue-300 ring-blue-200' : 'bg-amber-50 dark:bg-amber-950/40 text-amber-800 dark:text-amber-300 ring-amber-200';

function Status({ status }) { return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset ${reportTone(status)}`}>{label(status)}</span>; }
function ActionCard({ icon: Icon, title, description, to, critical = false }) { return <Link to={to} className={`group rounded-2xl border p-4 transition hover:-translate-y-0.5 hover:shadow-md ${critical ? 'border-red-200 bg-red-50/70 hover:border-red-300 dark:border-red-900 dark:bg-red-950/30 dark:hover:border-red-700' : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 hover:border-civic-300'}`}><div className="flex gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${critical ? 'bg-red-600 text-white' : 'bg-civic-50 dark:bg-civic-500/10 text-civic-700 dark:text-civic-300'}`}><Icon size={21} /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h2 className="font-bold text-ink dark:text-slate-100">{title}</h2><ChevronRight size={17} className="text-slate-400 dark:text-slate-500 transition group-hover:translate-x-0.5" /></div><p className="mt-1 text-sm leading-5 text-slate-500 dark:text-slate-400">{description}</p></div></div></Link>; }
function Empty({ title, detail, action, to }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50/70 p-6 text-center dark:border-slate-600 dark:bg-surface-2"><p className="font-semibold text-ink dark:text-slate-100">{title}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{detail}</p>{action && <Link to={to} className="mt-3 inline-block text-sm font-bold text-civic-700 dark:text-civic-300 hover:text-civic-800">{action}</Link>}</div>; }

export default function CitizenDashboard() {
  const { user } = useAuth(); const navigate = useNavigate();
  const [data, setData] = useState({ reports: [], attention: [], stats: null, emergencies: [], alerts: [], notifications: [], facilities: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const latestRequest = useRef(0);
  const load = useCallback(async ({ silent = false } = {}) => {
    const requestId = ++latestRequest.current;
    if (silent) setRefreshing(true); else setLoading(true);
    try {
      // A directory or alert feed outage must not make a citizen's whole
      // dashboard disappear. Each card renders only data that actually loaded.
      const results = await Promise.allSettled([
        reportsApi.mine({ limit: 5, sort: 'updated' }), reportsApi.stats(), emergencyApi.list({ limit: 3 }),
        emergencyApi.alerts({ limit: 3 }), notificationsApi.list(), facilitiesApi.list({ limit: 3 }),
        reportsApi.mine({ status: 'completed', limit: 2, sort: 'updated' })
      ]);
      const body = (index) => results[index].status === 'fulfilled' ? results[index].value.data : {};
      const failures = results.filter((result) => result.status === 'rejected').length;
      if (requestId !== latestRequest.current) return;
      setData({ reports: body(0).reports || [], attention: body(6).reports || [], stats: body(1).stats || null, emergencies: body(2).emergencies || [], alerts: body(3).alerts || [], notifications: body(4).notifications || [], facilities: body(5).facilities || [] });
      setError(failures ? "Some dashboard information couldn't load. You can still use the available sections or try again." : '');
    } catch (loadError) { if (requestId === latestRequest.current) setError(apiMessage(loadError)); } finally { if (requestId === latestRequest.current) { setLoading(false); setRefreshing(false); } }
  }, []);
  useEffect(() => { load(); }, [load]);
  const { online, live } = useEmergencyEvents(() => load({ silent: true }));
  const firstName = user?.name?.trim()?.split(/\s+/)[0] || 'there'; const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
  const activeReports = useMemo(() => data.reports.filter((report) => activeReportStatuses.has(report.status)), [data.reports]);
  const activeEmergencies = useMemo(() => data.emergencies.filter((item) => activeEmergencyStatuses.has(item.status)), [data.emergencies]);
  const attention = useMemo(() => data.attention.filter((report) => report.citizenResolution?.status !== 'confirmed'), [data.attention]); const unread = data.notifications.filter((item) => !item.readAt).length;
  const activeReportCount = data.stats?.active ?? activeReports.length;
  // Figures for the AI card come from this page's own authorized fetches — never invented.
  const aiStats = useMemo(() => [
    { label: 'Active cases', value: activeReportCount },
    { label: 'Unread notifications', value: unread },
    { label: 'Nearby services', value: data.facilities.length }
  ], [activeReportCount, unread, data.facilities.length]);
  return <CitizenLayout title="Dashboard" unreadCount={unread}>{loading ? <SkeletonPage kpis={4} blocks={2} /> : <div className="space-y-6">
    <AIBriefingCard
      presetKey="citizen_dashboard"
      title="✦ CivicSync Intelligence"
      subtitle={`Hello ${firstName} — what needs your attention today?`}
      description="Ask about your cases, CivicSync services, safety information or notifications."
      stats={aiStats}
      actionLabel="Ask CivicSync AI"
      loading={loading}
    />
    {!online && <div role="status" className="flex items-center gap-2 rounded-xl border border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/40 px-4 py-3 text-sm font-medium text-amber-900"><TriangleAlert size={17} /> You are offline. Information shown may be out of date until your connection returns.</div>}
    {error && <div role="alert" className="rounded-xl border border-red-200 dark:border-red-900 bg-red-50 dark:bg-red-950/40 p-4 text-sm text-red-800 dark:text-red-300">{error}<button onClick={() => load()} className="ml-3 font-bold underline">Retry</button></div>}
    <section className="relative overflow-hidden rounded-3xl bg-ink px-6 py-7 text-white shadow-lg sm:px-8"><div className="relative max-w-2xl"><p className="text-sm font-semibold text-civic-200">{greeting}, {firstName}</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Your community, in view.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300 dark:text-slate-400">Track your reports, find nearby help, and get important local safety updates in one protected place.</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-300 dark:text-slate-400"><span className={`h-2 w-2 rounded-full ${live ? 'bg-emerald-400' : 'bg-slate-400'}`} /> {live ? 'Live updates connected' : 'Updates will refresh automatically'}</div></div><div className="pointer-events-none absolute -right-16 -top-20 h-60 w-60 rounded-full bg-civic-500/20 blur-3xl" /></section>
    <section aria-label="Quick actions" className="grid gap-3 md:grid-cols-3"><ActionCard icon={Plus} title="Report an issue" description="Submit a civic concern with location and evidence." to="/dashboard/citizen/reports/new" /><ActionCard icon={Siren} title="Emergency help" description="Request immediate assistance. Use only for emergencies." to="/dashboard/citizen/emergency/new" critical /><ActionCard icon={MapPinned} title="Nearby services" description="Find registered hospitals, police, fire and safety services." to="/dashboard/citizen/nearby-services" /></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[ClipboardList, 'Active reports', data.stats ? activeReportCount : '—'], [Clock3, 'Under review', data.stats ? data.stats.underReview || 0 : '—'], [CheckCircle2, 'Resolved', data.stats ? data.stats.resolved || 0 : '—'], [Bell, 'Unread updates', unread]].map(([Icon, title, value]) => <div key={title} className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500 dark:text-slate-400">{title}</p><span className="grid h-9 w-9 place-items-center rounded-xl bg-civic-50 dark:bg-civic-500/10 text-civic-700 dark:text-civic-300"><Icon size={18} /></span></div><p className="mt-4 text-3xl font-extrabold text-ink dark:text-slate-100">{value}</p></div>)}</section>
    {activeEmergencies.length > 0 && <section className="rounded-2xl border border-red-200 dark:border-red-900 bg-red-50 dark:bg-red-950/40 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-600 text-white"><Siren size={20} /></span><div><h2 className="font-bold text-red-950 dark:text-red-100">Emergency status</h2><p className="mt-1 text-sm text-red-800 dark:text-red-300">You have an active emergency request. Follow its live status for the latest response information.</p></div></div><Link to={`/dashboard/citizen/emergency/${activeEmergencies[0]._id}`} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-bold text-white">View emergency</Link></div></section>}
    {attention.length > 0 && <section className="rounded-2xl border border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/40 p-5"><div className="flex items-start gap-3"><TriangleAlert className="mt-0.5 text-amber-700 dark:text-amber-300" size={20} /><div className="min-w-0 flex-1"><h2 className="font-bold text-amber-950 dark:text-amber-100">Needs your attention</h2>{attention.slice(0, 2).map((report) => <div key={report._id} className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-white/70 px-3 py-2 dark:bg-surface/70"><span className="min-w-0 text-sm text-amber-950 dark:text-amber-100"><b>{report.title}</b> is awaiting your resolution review.</span><Link className="text-sm font-bold text-amber-800 dark:text-amber-300" to={`/dashboard/citizen/reports/${report._id}`}>Review</Link></div>)}</div></div></section>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.8fr)]"><section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-ink dark:text-slate-100">My active reports</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">The latest status of reports you submitted.</p></div><Link to="/dashboard/citizen/reports" className="text-sm font-bold text-civic-700 dark:text-civic-300">View all</Link></div><div className="mt-5 space-y-3">{activeReports.length ? activeReports.map((report) => <button key={report._id} onClick={() => navigate(`/dashboard/citizen/reports/${report._id}`)} className="w-full rounded-xl border border-slate-200 dark:border-slate-700 p-4 text-left transition hover:border-civic-300 hover:bg-civic-50/30"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-bold text-ink dark:text-slate-100">{report.title}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{label(report.category)} · {report.departmentName || 'Assignment pending'}</p></div><Status status={report.status} /></div><p className="mt-3 text-xs text-slate-500 dark:text-slate-400">Updated {dateTime(report.updatedAt)}</p></button>) : <Empty title="No active reports" detail="You have not submitted any active civic reports." action="Report an issue" to="/dashboard/citizen/reports/new" />}</div></section><section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-ink dark:text-slate-100">Safety alerts</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Authorized public advisories.</p></div><Link to="/dashboard/citizen/alerts" className="text-sm font-bold text-civic-700 dark:text-civic-300">All alerts</Link></div><div className="mt-5 space-y-3">{data.alerts.length ? data.alerts.slice(0, 3).map((alert) => <Link key={alert._id} to="/dashboard/citizen/alerts" className="block rounded-xl border border-slate-200 dark:border-slate-700 p-3 transition hover:border-civic-300"><div className="flex items-start gap-3"><ShieldAlert size={18} className="mt-0.5 text-civic-700 dark:text-civic-300" /><div><p className="font-semibold text-ink dark:text-slate-100">{alert.title}</p><p className="mt-1 line-clamp-2 text-sm text-slate-500 dark:text-slate-400">{alert.description}</p><p className="mt-2 text-xs text-slate-400 dark:text-slate-500">Issued {dateTime(alert.createdAt)}</p></div></div></Link>) : <Empty title="No active safety alerts" detail="You are all caught up with current public alerts." />}</div></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-ink dark:text-slate-100">Nearby services</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Registered facilities only. Share location to sort by distance.</p></div><Link to="/dashboard/citizen/nearby-services" className="text-sm font-bold text-civic-700 dark:text-civic-300">Explore</Link></div><div className="mt-4">{data.facilities.length ? data.facilities.map((facility) => <Link key={facility._id} to="/dashboard/citizen/nearby-services" className="flex items-center gap-3 border-t border-slate-100 dark:border-slate-800 py-3 first:border-t-0 first:pt-0"><Hospital size={18} className="text-civic-700 dark:text-civic-300" /><div><p className="font-semibold text-ink dark:text-slate-100">{facility.name}</p><p className="text-xs text-slate-500 dark:text-slate-400">{label(facility.type)}{facility.address ? ` · ${facility.address}` : ''}</p></div></Link>) : <Empty title="Services are not available yet" detail="The directory will show registered locations when they are published." />}</div></section><section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-ink dark:text-slate-100">Recent updates</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Your case, emergency and system notifications.</p></div><Link to="/dashboard/citizen/notifications" className="text-sm font-bold text-civic-700 dark:text-civic-300">View all</Link></div><div className="mt-4">{data.notifications.length ? data.notifications.slice(0, 4).map((item) => <Link key={item._id} to="/dashboard/citizen/notifications" className="block border-t border-slate-100 dark:border-slate-800 py-3 first:border-t-0 first:pt-0"><p className={`text-sm ${item.readAt ? 'text-slate-600 dark:text-slate-300' : 'font-semibold text-ink dark:text-slate-100'}`}>{item.message}</p><p className="mt-1 text-xs text-slate-400 dark:text-slate-500">{dateTime(item.createdAt)}</p></Link>) : <Empty title="You're all caught up" detail="No new notifications right now." />}</div></section></div>
    <div className="flex justify-end"><button onClick={() => load({ silent: true })} disabled={refreshing} className="text-sm font-semibold text-slate-500 dark:text-slate-400 hover:text-civic-700 hover:text-civic-300 disabled:opacity-50">{refreshing ? 'Refreshing...' : 'Refresh dashboard'}</button></div>
  </div>}</CitizenLayout>;
}
