import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import CitizenLayout from '../../components/citizen/CitizenLayout.jsx';
import api, { apiMessage } from '../../services/api.js';
import { notificationsApi } from '../../services/notificationService.js';

export default function CitizenAccount() {
  const { section } = useParams(); const [profile, setProfile] = useState(null); const [notifications, setNotifications] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (section === 'notifications') notificationsApi.list().then(({ data }) => setNotifications(data.notifications)).catch((e) => setError(apiMessage(e))); else api.get('/users/me').then(({ data }) => setProfile(data)).catch((e) => setError(apiMessage(e))); }, [section]);
  async function saveProfile(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const { data } = await api.patch('/users/me', { name: form.get('name'), photoURL: form.get('photoURL') }); setProfile((p) => ({ ...p, user: data.user })); setMessage('Profile saved.'); } catch (e) { setError(apiMessage(e)); } }
  async function savePreference(event) { const emailNotifications = event.target.checked; try { await api.patch('/users/me/preferences', { emailNotifications }); setProfile((p) => ({ ...p, preferences: { emailNotifications } })); } catch (e) { setError(apiMessage(e)); } }
  if (section === 'notifications') return <CitizenLayout title="Notifications"><div className="mb-4 flex justify-end"><button onClick={async () => { await notificationsApi.readAll(); setNotifications((x) => x.map((n) => ({ ...n, readAt: new Date().toISOString() }))); }} className="font-bold text-civic-600">Mark all as read</button></div>{error && <p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="space-y-3">{notifications.length ? notifications.map((n) => <button key={n._id} onClick={async () => { if (!n.readAt) { await notificationsApi.read(n._id); setNotifications((x) => x.map((i) => i._id === n._id ? { ...i, readAt: new Date().toISOString() } : i)); } }} className={`block w-full rounded-xl border p-4 text-left ${n.readAt ? 'border-slate-200 bg-white' : 'border-civic-200 bg-civic-50'}`}><p className="font-semibold text-ink">{n.message}</p><p className="mt-1 text-xs text-slate-500">{new Date(n.createdAt).toLocaleString()} {!n.readAt && '· Unread'}</p></button>) : <div className="rounded-xl bg-white p-10 text-center text-slate-500">No notifications yet.</div>}</div></CitizenLayout>;
  const user = profile?.user; return <CitizenLayout title={section === 'settings' ? 'Settings' : 'My profile'}>{error && <p className="mb-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{!user ? <p className="text-slate-500">Loading account…</p> : section === 'settings' ? <section className="max-w-xl rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-ink">Notification preferences</h2><label className="mt-5 flex items-center justify-between gap-4"><span><span className="block font-semibold">Email notifications</span><span className="text-sm text-slate-500">Receive email when your report status changes.</span></span><input className="h-5 w-5" type="checkbox" checked={profile.preferences?.emailNotifications ?? true} onChange={savePreference} /></label></section> : <form onSubmit={saveProfile} className="max-w-xl rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-ink">Account details</h2><label className="mt-4 block text-sm font-semibold">Name<input name="name" defaultValue={user.name} maxLength="80" /></label><label className="mt-4 block text-sm font-semibold">Profile photo URL<input name="photoURL" defaultValue={user.photoURL} /></label><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Email</span><br />{user.email}</p><p><span className="text-slate-500">Role</span><br />Citizen</p><p><span className="text-slate-500">Account status</span><br />{user.status}</p><p><span className="text-slate-500">Registered</span><br />{new Date(user.createdAt).toLocaleDateString()}</p></div>{message && <p className="mt-4 text-sm text-emerald-700">{message}</p>}<button className="mt-5 rounded-lg bg-civic-600 px-4 py-2.5 font-bold text-white">Save profile</button></form>}</CitizenLayout>;
}
