import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ComplaintForm from '../components/ComplaintForm.jsx';
import ComplaintList from '../components/ComplaintList.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import api, { apiMessage } from '../services/api.js';

export default function Dashboard() {
  const { user, logout } = useAuth(); const navigate = useNavigate();
  const [complaints, setComplaints] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  async function load() { setLoading(true); setError(''); try { const { data } = await api.get('/complaints'); setComplaints(data.complaints); } catch (err) { setError(apiMessage(err)); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function save(values) { setBusy(true); setError(''); try { if (editing) { const { data } = await api.put(`/complaints/${editing._id}`, values); setComplaints((items) => items.map((x) => x._id === data.complaint._id ? data.complaint : x)); setEditing(null); } else { const { data } = await api.post('/complaints', values); setComplaints((items) => [data.complaint, ...items]); } } catch (err) { setError(apiMessage(err)); } finally { setBusy(false); } }
  async function remove(item) { if (!window.confirm(`Delete “${item.title}”? This cannot be undone.`)) return; setError(''); try { await api.delete(`/complaints/${item._id}`); setComplaints((items) => items.filter((x) => x._id !== item._id)); if (editing?._id === item._id) setEditing(null); } catch (err) { setError(apiMessage(err)); } }
  async function signOut() { await logout(); navigate('/login'); }
  return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="text-xs font-bold tracking-[0.2em] text-civic-600">CIVICSYNC</p><p className="font-bold text-ink">Citizen service portal</p></div><button onClick={signOut} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold hover:bg-slate-50">Logout</button></div></header><main className="mx-auto max-w-7xl p-5 sm:p-8"><section className="mb-7 rounded-2xl bg-ink p-6 text-white shadow-lg"><div className="flex flex-wrap items-center gap-4"><div className="flex-1"><p className="text-civic-50">Signed in and protected</p><h1 className="mt-1 text-3xl font-bold">Welcome, {user.name}</h1><div className="mt-4 flex flex-wrap gap-x-6 gap-y-1 text-sm text-slate-300"><span>Email: {user.email}</span><span>Role: {user.role}</span><span>Status: {user.status}</span></div></div>{user.photoURL && <img src={user.photoURL} alt="Profile" className="h-14 w-14 rounded-full border-2 border-civic-300 object-cover" referrerPolicy="no-referrer" />}</div></section><div className="grid gap-7 lg:grid-cols-[minmax(320px,0.8fr)_minmax(0,1.7fr)]"><ComplaintForm complaint={editing} onSubmit={save} onCancel={() => setEditing(null)} busy={busy} /><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="mb-4"><h2 className="font-bold text-ink">My civic complaints</h2><p className="mt-1 text-sm text-slate-500">Track the issues you have reported.</p></div>{error && <p className="mb-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<ComplaintList complaints={complaints} loading={loading} onEdit={setEditing} onDelete={remove} /></section></div></main></div>;
}
