import { Router } from 'express';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { assignDepartmentHead, assignEmergencyDepartmentHead, createDepartment, deleteComplaint, deleteDepartment, deleteUser, exportReport, getAnalytics, getComplaintDetail, getDashboardStats, getDepartmentDetail, getEmergencyDetail, getSettings, getUserDetail, listActivityLogs, listComplaints, listDepartments, listDepartmentsForCitizen, listEmergencies, listUsers, selectUsers, updateComplaint, updateDepartment, updateEmergency, updateEmergencyRouting, updateSettings, updateUserRole, updateUserStatus } from '../controllers/adminController.js';

const router = Router();
router.use(requireAuth, requireRole('admin'));
router.get('/dashboard', getDashboardStats);
router.get('/analytics', getAnalytics);
router.get('/reports/export', exportReport);
router.get('/users/select', selectUsers);
router.get('/users', listUsers);
router.get('/users/:id', getUserDetail);
router.patch('/users/:id/role', updateUserRole);
router.patch('/users/:id/status', updateUserStatus);
router.delete('/users/:id', deleteUser);
router.get('/departments', listDepartments);
router.post('/departments', createDepartment);
router.get('/departments/citizen-list', listDepartmentsForCitizen);
router.get('/departments/:id', getDepartmentDetail);
router.patch('/departments/:id', updateDepartment);
router.post('/departments/:id/head', assignDepartmentHead);
router.post('/departments/:id/emergency-head', assignEmergencyDepartmentHead);
router.patch('/departments/:id/emergency-routing', updateEmergencyRouting);
router.delete('/departments/:id', deleteDepartment);
router.get('/complaints', listComplaints);
router.get('/complaints/:id', getComplaintDetail);
router.patch('/complaints/:id', updateComplaint);
router.delete('/complaints/:id', deleteComplaint);
router.get('/emergencies', listEmergencies);
router.get('/emergencies/:id', getEmergencyDetail);
router.patch('/emergencies/:id', updateEmergency);
router.get('/activity-logs', listActivityLogs);
router.get('/settings', getSettings);
router.patch('/settings', updateSettings);
export default router;
