import { Router } from 'express';
import { addAssignmentWorkers, analytics, assignEmergency, backupEmergency, classifyRequest, closeEmergency, communityVerify, createAlert, createCategory, createContact, createEmergency, createAlertManaged, dashboard, deleteAlertManaged, deleteCategory, deleteContact, downloadEvidence, emergencyTypes, escalateEmergency, getEmergency, hotspots, listAlerts, listAssignableResponders, listContacts, listEmergencies, manageCategories, mapEmergencies, mergeEmergency, nearbyResponderTeams, responderLocations, responderPositions, resolveEmergency, safetyIntelligence, similarEmergencies, updateAlert, updateAlertManaged, updateAssignmentStatus, updateCategory, updateContact, updateEmergency, updateResponderLocation, updateStatus, uploadEvidence } from '../controllers/emergencyController.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { uploadEmergencyEvidence } from '../middleware/uploadMiddleware.js';

const router = Router();
router.use(requireAuth);
router.get('/types', emergencyTypes);
router.get('/categories/manage', manageCategories);
router.post('/categories', createCategory);
router.patch('/categories/:id', updateCategory);
router.delete('/categories/:id', deleteCategory);
router.post('/classify', classifyRequest);
router.get('/assignable-responders', listAssignableResponders);
router.get('/map', mapEmergencies);
router.get('/responder-locations', responderLocations);
router.get('/hotspots', hotspots);
router.get('/safety-intelligence', safetyIntelligence);
router.get('/analytics', analytics);
router.get('/dashboard', dashboard);
router.get('/alerts', listAlerts);
router.post('/alerts', createAlertManaged);
router.patch('/alerts/:id', updateAlertManaged);
router.delete('/alerts/:id', deleteAlertManaged);
router.post('/', createEmergency);
router.get('/', listEmergencies);
router.get('/:id', getEmergency);
router.get('/:id/similar', similarEmergencies);
router.post('/:id/merge', mergeEmergency);
router.get('/:id/responders', nearbyResponderTeams);
router.get('/:id/responder-positions', responderPositions);
router.post('/:id/verify', communityVerify);
router.get('/:id/evidence/:filename', downloadEvidence);
router.post('/:id/evidence', uploadEmergencyEvidence, uploadEvidence);
router.patch('/:id/responder-location', updateResponderLocation);
router.patch('/:id', updateEmergency);
router.post('/:id/assign', assignEmergency);
router.patch('/:id/assignments/:assignmentId/status', updateAssignmentStatus);
router.post('/:id/assignments/:assignmentId/workers', addAssignmentWorkers);
router.patch('/:id/status', updateStatus);
router.post('/:id/escalate', escalateEmergency);
router.post('/:id/backup', backupEmergency);
router.post('/:id/resolve', resolveEmergency);
router.post('/:id/close', closeEmergency);

export const contactRouter = Router();
contactRouter.use(requireAuth, requireRole('citizen'));
contactRouter.get('/', listContacts);
contactRouter.post('/', createContact);
contactRouter.patch('/:id', updateContact);
contactRouter.delete('/:id', deleteContact);
export default router;
