import { Router } from 'express';
import { createReport, deleteReport, getLegacyReportAttachment, getReport, getReportAttachment, listDepartments, listMyReports, reportStats, updateReport, verifyReportResolution, submitReportFeedback } from '../controllers/reportController.js';
import { requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { uploadReportMedia } from '../middleware/uploadMiddleware.js';

const router = Router();
const reportFileRouter = Router();
reportFileRouter.use(requireAuth);
reportFileRouter.get('/:id/attachments/:filename', getReportAttachment);
router.use(requireAuth, requireRole('citizen'));
router.get('/departments', listDepartments);
router.post('/', uploadReportMedia, createReport);
router.get('/my/stats', reportStats);
router.get('/my', listMyReports);
router.get('/:id', getReport);
router.post('/:id/verify-resolution', verifyReportResolution);
router.post('/:id/feedback', submitReportFeedback);
router.put('/:id', uploadReportMedia, updateReport);
router.delete('/:id', deleteReport);
export { reportFileRouter };
export default router;
