import mongoose from 'mongoose';
import User from '../models/User.js';
import Department from '../models/Department.js';
import Report from '../models/Report.js';
import Emergency from '../models/Emergency.js';
import ActivityLog from '../models/ActivityLog.js';
import SystemSetting from '../models/SystemSetting.js';
import { reportPriorities, reportStatuses } from '../config/reportOptions.js';
import { emergencyStatuses } from '../config/emergencyOptions.js';

const roles = ['citizen', 'admin', 'department_head', 'department_officer', 'officer', 'field_worker', 'emergency_department_head', 'emergency_department_officer', 'emergency_officer', 'emergency_field_worker'];
const departmentHeadRoles = ['department_head', 'emergency_department_head'];
const emergencyRoles = ['emergency_department_head', 'emergency_department_officer', 'emergency_officer', 'emergency_field_worker'];
const userStatuses = ['active', 'suspended'];
const emergencyTypes = ['police', 'fire', 'medical', 'accident', 'disaster', 'other'];
const statusLabels = Object.fromEntries(reportStatuses.map((value) => [value, value.replaceAll('_', ' ')]));
const transitionMap = { pending: ['verified'], verified: ['assigned'], assigned: ['in_progress'], in_progress: ['under_review'], under_review: ['completed'], completed: ['closed'], closed: [] };

function objectId(value) { return mongoose.Types.ObjectId.isValid(value); }
function escapeRegex(value = '') { return value.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function pageOf(value) { return Math.max(1, Number(value) || 1); }
function limitOf(value) { return Math.min(50, Math.max(1, Number(value) || 15)); }
function dateRange(value) { const days = { '7d': 7, '30d': 30, '3m': 90, '6m': 180, '1y': 365 }[value] || 30; const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - days); const previousStart = new Date(start); previousStart.setDate(previousStart.getDate() - days); return { start, end, previousStart, days }; }
function safeUser(user) { return { id: user._id, name: user.name, email: user.email, phone: user.phone || '', photoURL: user.photoURL || '', role: user.role, department: user.department, departmentName: user.departmentName || '', status: user.status, createdAt: user.createdAt }; }
async function log(admin, action, targetType, targetId, targetName, description, metadata = {}) { await ActivityLog.create({ admin: admin._id || admin, action, targetType, targetId, targetName, description, metadata }); }
function reportFilter(query = {}) { const filter = {}; if (reportStatuses.includes(query.status)) filter.status = query.status; if (reportPriorities.includes(query.priority)) filter.priority = query.priority; if (query.department?.trim()) filter.departmentName = query.department.trim(); if (query.category?.trim()) filter.category = query.category.trim(); if (query.from || query.to) { filter.createdAt = {}; if (query.from && !Number.isNaN(Date.parse(query.from))) filter.createdAt.$gte = new Date(query.from); if (query.to && !Number.isNaN(Date.parse(query.to))) { const end = new Date(query.to); end.setHours(23, 59, 59, 999); filter.createdAt.$lte = end; } } if (query.search?.trim()) { const expression = new RegExp(escapeRegex(query.search), 'i'); filter.$or = [{ title: expression }, { description: expression }, { departmentName: expression }]; } return filter; }
function reportQuery(filter) { return Report.find(filter).populate('createdBy', 'name email phone photoURL').populate('assignedOfficer', 'name email phone photoURL').populate('assignedFieldWorker', 'name email phone photoURL'); }

async function analyticsTrends(start, days) { const format = days > 90 ? '%Y-%m' : '%Y-%m-%d'; const [complaintTrend, emergencyTrend, userGrowth] = await Promise.all([Report.aggregate([{ $match: { createdAt: { $gte: start } } }, { $group: { _id: { $dateToString: { format, date: '$createdAt' } }, count: { $sum: 1 } } }, { $sort: { _id: 1 } }]), Emergency.aggregate([{ $match: { createdAt: { $gte: start } } }, { $group: { _id: { $dateToString: { format, date: '$createdAt' } }, count: { $sum: 1 } } }, { $sort: { _id: 1 } }]), User.aggregate([{ $match: { createdAt: { $gte: start } } }, { $group: { _id: { $dateToString: { format, date: '$createdAt' } }, count: { $sum: 1 } } }, { $sort: { _id: 1 } }])]); return { complaintTrend, emergencyTrend, userGrowth }; }

export async function getDashboardStats(req, res, next) {
  try {
    const { start, previousStart, days } = dateRange(req.query.range); const current = { createdAt: { $gte: start } }; const previous = { createdAt: { $gte: previousStart, $lt: start } };
    const [users, departments, reportRows, emergencyRows, roleRows, currentReports, previousReports, currentUsers, previousUsers, recentReports, recentEmergencies, departmentPerformance] = await Promise.all([
      User.countDocuments(), Department.countDocuments(), Report.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]), Emergency.aggregate([{ $group: { _id: '$status', count: { $sum: 1 } } }]), User.aggregate([{ $group: { _id: '$role', count: { $sum: 1 } } }]), Report.countDocuments(current), Report.countDocuments(previous), User.countDocuments(current), User.countDocuments(previous), reportQuery({}).sort({ createdAt: -1 }).limit(6).lean(), Emergency.find().populate('citizen', 'name email phone photoURL').populate('assignedDepartment', 'name').populate('assignedOfficer', 'name email').sort({ createdAt: -1 }).limit(6).lean(),
      Report.aggregate([
        { $group: {
          _id: '$departmentName', total: { $sum: 1 },
          resolved: { $sum: { $cond: [{ $in: ['$status', ['completed', 'closed']] }, 1, 0] } },
          pending: { $sum: { $cond: [{ $in: ['$status', ['pending', 'verified', 'assigned', 'in_progress', 'under_review']] }, 1, 0] } }
        } },
        { $project: { department: '$_id', total: 1, resolved: 1, pending: 1 } },
        { $sort: { total: -1 } }, { $limit: 8 }
      ])
    ]);
    const statuses = Object.fromEntries(reportRows.map((row) => [row._id, row.count])); const emergencies = Object.fromEntries(emergencyRows.map((row) => [row._id, row.count])); const roleCounts = Object.fromEntries(roleRows.map((row) => [row._id, row.count])); const reportTotal = reportRows.reduce((sum, row) => sum + row.count, 0); const completed = (statuses.completed || 0) + (statuses.closed || 0); const trend = await analyticsTrends(start, days); const percentage = (now, before) => before ? Math.round(((now - before) / before) * 1000) / 10 : now ? 100 : 0;
    res.json({ success: true, dashboard: { cards: { totalUsers: users, totalCitizens: roleCounts.citizen || 0, totalDepartments: departments, totalDepartmentHeads: roleCounts.department_head || 0, totalDepartmentOfficers: roleCounts.department_officer || 0, totalOfficers: roleCounts.officer || 0, totalFieldWorkers: roleCounts.field_worker || 0, totalComplaints: reportTotal, pendingComplaints: statuses.pending || 0, activeComplaints: (statuses.assigned || 0) + (statuses.in_progress || 0) + (statuses.under_review || 0), completedComplaints: completed, totalEmergencies: emergencyRows.reduce((sum, row) => sum + row.count, 0), activeEmergencies: (emergencies.active || 0) + (emergencies.in_progress || 0) }, roleCounts, changes: { complaints: percentage(currentReports, previousReports), users: percentage(currentUsers, previousUsers) }, statusDistribution: reportRows, departmentPerformance, recentReports, recentEmergencies, resolutionRate: reportTotal ? Math.round((completed / reportTotal) * 100) : 0, ...trend } });
  } catch (error) { next(error); }
}

export async function getAnalytics(req, res, next) {
  try {
    const { start, days } = dateRange(req.query.range); const filter = { createdAt: { $gte: start } };
    if (req.query.department?.trim()) filter.departmentName = req.query.department.trim();
    if (reportStatuses.includes(req.query.status)) filter.status = req.query.status;
    if (req.query.category?.trim()) filter.category = req.query.category.trim();
    const [statusDistribution, byCategory, performance, responseTime, trends] = await Promise.all([
      Report.aggregate([{ $match: filter }, { $group: { _id: '$status', count: { $sum: 1 } } }]),
      Report.aggregate([{ $match: filter }, { $group: { _id: '$category', count: { $sum: 1 } } }, { $sort: { count: -1 } }, { $limit: 8 }]),
      Report.aggregate([{ $match: filter }, { $group: { _id: '$departmentName', total: { $sum: 1 }, resolved: { $sum: { $cond: [{ $in: ['$status', ['completed', 'closed']] }, 1, 0] } } } }, { $project: { department: '$_id', total: 1, resolved: 1 } }, { $sort: { total: -1 } }]),
      Emergency.aggregate([{ $match: { createdAt: { $gte: start }, responseTimeMinutes: { $ne: null } } }, { $group: { _id: null, average: { $avg: '$responseTimeMinutes' } } }]), analyticsTrends(start, days)
    ]);
    res.json({ success: true, analytics: { statusDistribution, byCategory, departmentPerformance: performance, averageEmergencyResponseMinutes: Math.round(responseTime[0]?.average || 0), ...trends } });
  } catch (error) { next(error); }
}

export async function listUsers(req, res, next) { try { const filter = {}; const { search = '', role = '', status = '' } = req.query; if (roles.includes(role)) filter.role = role; if (userStatuses.includes(status)) filter.status = status; if (search.trim()) { const expression = new RegExp(escapeRegex(search), 'i'); filter.$or = [{ name: expression }, { email: expression }, { phone: expression }]; } const page = pageOf(req.query.page); const limit = limitOf(req.query.limit); const [items, total] = await Promise.all([User.find(filter).populate('department', 'name').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), User.countDocuments(filter)]); res.json({ success: true, users: items.map(safeUser), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function selectUsers(req, res, next) { try { const filter = { status: 'active' }; if (req.query.q?.trim()) { const expression = new RegExp(escapeRegex(req.query.q), 'i'); filter.$or = [{ name: expression }, { email: expression }]; } const users = await User.find(filter).select('name email role department departmentName photoURL').populate('department', 'name').sort({ name: 1 }).limit(20).lean(); res.json({ success: true, users: users.map(safeUser) }); } catch (error) { next(error); } }
export async function getUserDetail(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'User not found.' }); const user = await User.findById(req.params.id).populate('department', 'name').lean(); if (!user) return res.status(404).json({ success: false, message: 'User not found.' }); const [complaints, complaintStats, emergencies, activity] = await Promise.all([Report.countDocuments({ createdBy: user._id }), Report.aggregate([{ $match: { createdBy: user._id } }, { $group: { _id: '$status', count: { $sum: 1 } } }]), Emergency.countDocuments({ citizen: user._id }), ActivityLog.find({ targetId: user._id }).populate('admin', 'name email photoURL').sort({ createdAt: -1 }).limit(10).lean()]); res.json({ success: true, user: safeUser(user), stats: { complaints, complaintByStatus: complaintStats, emergencies }, activity }); } catch (error) { next(error); } }
export async function updateUserRole(req, res, next) { try { const { role, departmentId } = req.body; if (!roles.includes(role) || departmentHeadRoles.includes(role)) return res.status(400).json({ success: false, message: 'Department heads must be assigned from their department.' }); if (!objectId(req.params.id) || req.user._id.equals(req.params.id)) return res.status(400).json({ success: false, message: 'This user role cannot be changed.' }); const user = await User.findById(req.params.id); if (!user) return res.status(404).json({ success: false, message: 'User not found.' }); let department = null; if (departmentId) { if (!objectId(departmentId)) return res.status(400).json({ success: false, message: 'Invalid department.' }); department = await Department.findById(departmentId); if (!department) return res.status(404).json({ success: false, message: 'Department not found.' }); if (emergencyRoles.includes(role) && !['emergency', 'hybrid'].includes(department.scope)) return res.status(400).json({ success: false, message: 'Emergency staff must belong to an emergency-enabled department.' }); if (!emergencyRoles.includes(role) && role !== 'citizen' && department.scope === 'emergency') return res.status(400).json({ success: false, message: 'Civic staff must belong to a civic or hybrid department.' }); } else if (role !== 'citizen' && role !== 'admin') return res.status(400).json({ success: false, message: 'A department is required for this operational role.' }); const previousRole = user.role; await Department.updateMany({ $or: [{ head: user._id }, { emergencyHead: user._id }] }, { $set: { head: null, emergencyHead: null } }); user.role = role; user.department = department?._id || null; user.departmentName = department?.name || ''; await user.save(); await log(req.user, 'role_changed', 'user', user._id, user.name, `Role changed from ${previousRole} to ${role}.`, { previousRole, role }); res.json({ success: true, message: 'User role updated.', user: safeUser(user) }); } catch (error) { next(error); } }
export async function updateUserStatus(req, res, next) { try { if (!userStatuses.includes(req.body.status) || !objectId(req.params.id) || req.user._id.equals(req.params.id)) return res.status(400).json({ success: false, message: 'This account status cannot be changed.' }); const user = await User.findById(req.params.id); if (!user) return res.status(404).json({ success: false, message: 'User not found.' }); user.status = req.body.status; await user.save(); await log(req.user, user.status === 'suspended' ? 'user_blocked' : 'user_unblocked', 'user', user._id, user.name, `Account ${user.status}.`); res.json({ success: true, message: 'Account status updated.', user: safeUser(user) }); } catch (error) { next(error); } }
export async function deleteUser(req, res, next) { try { if (!objectId(req.params.id) || req.user._id.equals(req.params.id)) return res.status(400).json({ success: false, message: 'This user cannot be deleted.' }); const user = await User.findById(req.params.id); if (!user) return res.status(404).json({ success: false, message: 'User not found.' }); if (user.role === 'admin') return res.status(400).json({ success: false, message: 'Administrator accounts cannot be deleted.' }); await Department.updateMany({ $or: [{ head: user._id }, { emergencyHead: user._id }] }, { $set: { head: null, emergencyHead: null } }); await log(req.user, 'user_deleted', 'user', user._id, user.name, `User ${user.email} deleted.`); await user.deleteOne(); res.json({ success: true, message: 'User deleted.' }); } catch (error) { next(error); } }

export async function listDepartmentsForCitizen(req, res, next) {
  try {
    const departments = await Department.find({ status: 'active' }).sort({ name: 1 }).lean();
    res.json({ success: true, departments });
  } catch (error) { next(error); }
}

export async function listDepartments(req, res, next) { try { const filter = {}; if (req.query.status === 'active' || req.query.status === 'inactive') filter.status = req.query.status; if (['civic', 'emergency', 'hybrid'].includes(req.query.scope)) filter.scope = req.query.scope; if (req.query.search?.trim()) filter.name = new RegExp(escapeRegex(req.query.search), 'i'); const page = pageOf(req.query.page); const limit = limitOf(req.query.limit); const [departments, total] = await Promise.all([Department.find(filter).populate('head', 'name email photoURL').populate('emergencyHead', 'name email photoURL').sort({ name: 1 }).skip((page - 1) * limit).limit(limit).lean(), Department.countDocuments(filter)]); res.json({ success: true, departments, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function getDepartmentDetail(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Department not found.' }); const department = await Department.findById(req.params.id).populate('head', 'name email phone photoURL').populate('emergencyHead', 'name email phone photoURL').lean(); if (!department) return res.status(404).json({ success: false, message: 'Department not found.' }); const [team, rows, monthly] = await Promise.all([User.find({ department: department._id, role: { $in: ['department_head', 'department_officer', 'officer', 'field_worker', 'emergency_department_head', 'emergency_department_officer', 'emergency_officer', 'emergency_field_worker'] } }).select('name email phone photoURL role status').lean(), Report.aggregate([{ $match: { departmentName: department.name } }, { $group: { _id: '$status', count: { $sum: 1 } } }]), Report.aggregate([{ $match: { departmentName: department.name } }, { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, total: { $sum: 1 }, resolved: { $sum: { $cond: [{ $in: ['$status', ['completed', 'closed']] }, 1, 0] } } } }, { $sort: { _id: 1 } }, { $limit: 12 }])]); const stats = Object.fromEntries(rows.map((row) => [row._id, row.count])); const total = rows.reduce((sum, row) => sum + row.count, 0); const resolved = (stats.completed || 0) + (stats.closed || 0); res.json({ success: true, department, team, stats: { total, pending: stats.pending || 0, active: (stats.assigned || 0) + (stats.in_progress || 0) + (stats.under_review || 0), completed: resolved, resolutionRate: total ? Math.round(resolved / total * 100) : 0, byStatus: rows }, monthly }); } catch (error) { next(error); } }
function departmentPayload(body) { const routingTypes = Array.isArray(body.emergencyTypes) ? body.emergencyTypes.filter((type) => emergencyTypes.includes(type)) : []; return { name: body.name?.trim(), type: body.type?.trim() || '', description: body.description?.trim() || '', contactNumber: body.contactNumber?.trim() || '', email: body.email?.trim().toLowerCase() || '', address: body.address?.trim() || '', status: body.status === 'inactive' ? 'inactive' : 'active', scope: ['civic', 'emergency', 'hybrid'].includes(body.scope) ? body.scope : 'civic', emergencyTypes: routingTypes }; }
function validDepartment(payload) { return payload.name && payload.name.length <= 120 && (!payload.email || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payload.email)) && (!payload.contactNumber || /^[+()\-\s\d]{6,30}$/.test(payload.contactNumber)); }
export async function createDepartment(req, res, next) { try { const payload = departmentPayload(req.body); if (!validDepartment(payload)) return res.status(400).json({ success: false, message: 'Provide a department name, valid email, and valid contact number.' }); const department = await Department.create(payload); await log(req.user, 'department_created', 'department', department._id, department.name, 'Department created.'); res.status(201).json({ success: true, message: 'Department created.', department }); } catch (error) { next(error); } }
export async function updateDepartment(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Department not found.' }); const department = await Department.findById(req.params.id); if (!department) return res.status(404).json({ success: false, message: 'Department not found.' }); const payload = departmentPayload({ ...department.toObject(), ...req.body }); if (!validDepartment(payload)) return res.status(400).json({ success: false, message: 'Provide a department name, valid email, and valid contact number.' }); const oldName = department.name; Object.assign(department, payload); await department.save(); if (oldName !== department.name) await Promise.all([User.updateMany({ department: department._id }, { $set: { departmentName: department.name } }), Report.updateMany({ departmentName: oldName }, { $set: { departmentName: department.name } })]); await log(req.user, 'department_updated', 'department', department._id, department.name, 'Department details updated.'); res.json({ success: true, message: 'Department updated.', department }); } catch (error) { next(error); } }
export async function assignDepartmentHead(req, res, next) { try { const { userId } = req.body; if (!objectId(req.params.id) || !objectId(userId)) return res.status(400).json({ success: false, message: 'Select a valid department and registered user.' }); const [department, candidate] = await Promise.all([Department.findById(req.params.id), User.findById(userId)]); if (!department || !candidate) return res.status(404).json({ success: false, message: 'Department or user not found.' }); if (candidate.status !== 'active' || candidate.role === 'admin') return res.status(400).json({ success: false, message: 'Only active non-admin users are eligible to lead a department.' }); const oldHead = department.head ? await User.findById(department.head) : null; await Department.updateMany({ head: candidate._id, _id: { $ne: department._id } }, { $set: { head: null } }); if (oldHead && !oldHead._id.equals(candidate._id)) { oldHead.role = 'citizen'; oldHead.department = null; oldHead.departmentName = ''; await oldHead.save(); } candidate.role = 'department_head'; candidate.department = department._id; candidate.departmentName = department.name; await candidate.save(); department.head = candidate._id; await department.save(); await log(req.user, oldHead ? 'department_head_changed' : 'department_head_assigned', 'department', department._id, department.name, `${candidate.name} assigned as department head.`, { previousHead: oldHead?._id || null, newHead: candidate._id }); await department.populate('head', 'name email phone photoURL'); res.json({ success: true, message: oldHead ? 'Department head changed.' : 'Department head assigned.', department }); } catch (error) { next(error); } }
export async function assignEmergencyDepartmentHead(req, res, next) { try { const { userId } = req.body; if (!objectId(req.params.id) || !objectId(userId)) return res.status(400).json({ success: false, message: 'Select a valid emergency department and registered user.' }); const [department, candidate] = await Promise.all([Department.findById(req.params.id), User.findById(userId)]); if (!department || !candidate) return res.status(404).json({ success: false, message: 'Department or user not found.' }); if (!['emergency', 'hybrid'].includes(department.scope) || candidate.status !== 'active' || candidate.role === 'admin') return res.status(400).json({ success: false, message: 'Choose an active non-admin user and an emergency-enabled department.' }); const previous = department.emergencyHead ? await User.findById(department.emergencyHead) : null; await Department.updateMany({ emergencyHead: candidate._id, _id: { $ne: department._id } }, { $set: { emergencyHead: null } }); if (previous && !previous._id.equals(candidate._id)) { previous.role = 'citizen'; previous.department = null; previous.departmentName = ''; await previous.save(); } candidate.role = 'emergency_department_head'; candidate.department = department._id; candidate.departmentName = department.name; await candidate.save(); department.emergencyHead = candidate._id; await department.save(); await log(req.user, previous ? 'emergency_department_head_changed' : 'emergency_department_head_assigned', 'department', department._id, department.name, `${candidate.name} assigned as emergency department head.`, { previousHead: previous?._id || null, newHead: candidate._id }); await department.populate('emergencyHead', 'name email phone photoURL'); res.json({ success: true, message: 'Emergency department head assigned.', department }); } catch (error) { next(error); } }
export async function updateEmergencyRouting(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Department not found.' }); const department = await Department.findById(req.params.id); if (!department) return res.status(404).json({ success: false, message: 'Department not found.' }); const types = Array.isArray(req.body.emergencyTypes) ? req.body.emergencyTypes.filter((type) => emergencyTypes.includes(type)) : []; if (!types.length) return res.status(400).json({ success: false, message: 'Select at least one valid emergency type.' }); department.scope = department.scope === 'civic' ? 'hybrid' : department.scope; department.emergencyTypes = [...new Set(types)]; await department.save(); await log(req.user, 'emergency_routing_updated', 'department', department._id, department.name, 'Emergency routing responsibilities updated.', { emergencyTypes: department.emergencyTypes }); res.json({ success: true, message: 'Emergency routing updated.', department }); } catch (error) { next(error); } }
export async function deleteDepartment(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Department not found.' }); const department = await Department.findById(req.params.id); if (!department) return res.status(404).json({ success: false, message: 'Department not found.' }); await User.updateMany({ department: department._id }, { $set: { role: 'citizen', department: null, departmentName: '' } }); await log(req.user, 'department_deleted', 'department', department._id, department.name, 'Department deleted.'); await department.deleteOne(); res.json({ success: true, message: 'Department deleted.' }); } catch (error) { next(error); } }

export async function listComplaints(req, res, next) { try { const filter = reportFilter(req.query); const page = pageOf(req.query.page); const limit = limitOf(req.query.limit); const [complaints, total] = await Promise.all([reportQuery(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Report.countDocuments(filter)]); res.json({ success: true, complaints, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function getComplaintDetail(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Complaint not found.' }); const complaint = await reportQuery({ _id: req.params.id }).populate('completionReport.submittedBy', 'name email photoURL').lean(); if (!complaint) return res.status(404).json({ success: false, message: 'Complaint not found.' }); res.json({ success: true, complaint }); } catch (error) { next(error); } }
export async function updateComplaint(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Complaint not found.' }); const complaint = await Report.findById(req.params.id); if (!complaint) return res.status(404).json({ success: false, message: 'Complaint not found.' }); const { status, priority, departmentName, officerId, fieldWorkerId, note = '' } = req.body; if (status !== undefined) { if (!reportStatuses.includes(status) || (status !== complaint.status && !transitionMap[complaint.status]?.includes(status))) return res.status(400).json({ success: false, message: `Invalid complaint status transition from ${statusLabels[complaint.status] || complaint.status}.` }); complaint.status = status; } if (priority !== undefined) { if (!reportPriorities.includes(priority)) return res.status(400).json({ success: false, message: 'Invalid priority.' }); complaint.priority = priority; } if (departmentName !== undefined) { const department = await Department.findOne({ name: departmentName, status: 'active', scope: { $in: ['civic', 'hybrid'] } }); if (!department) return res.status(400).json({ success: false, message: 'Choose an active civic department.' }); complaint.departmentName = department.name; } const assignedDepartment = complaint.departmentName; if (officerId !== undefined) { const officer = officerId ? await User.findOne({ _id: officerId, role: { $in: ['department_officer', 'officer'] }, departmentName: assignedDepartment, status: 'active' }) : null; if (officerId && !officer) return res.status(400).json({ success: false, message: 'Selected officer is not active in this department.' }); complaint.assignedOfficer = officer?._id || null; } if (fieldWorkerId !== undefined) { const worker = fieldWorkerId ? await User.findOne({ _id: fieldWorkerId, role: 'field_worker', departmentName: assignedDepartment, status: 'active' }) : null; if (fieldWorkerId && !worker) return res.status(400).json({ success: false, message: 'Selected field worker is not active in this department.' }); complaint.assignedFieldWorker = worker?._id || null; } if ((officerId || fieldWorkerId) && ['pending', 'verified'].includes(complaint.status)) complaint.status = 'assigned'; complaint.activity.push({ action: 'Updated by administrator', actorRole: 'admin', note: String(note).slice(0, 500) }); await complaint.save(); await log(req.user, 'complaint_updated', 'report', complaint._id, complaint.title, 'Complaint management data updated.'); await complaint.populate('createdBy', 'name email phone photoURL'); await complaint.populate('assignedOfficer', 'name email photoURL'); await complaint.populate('assignedFieldWorker', 'name email photoURL'); res.json({ success: true, message: 'Complaint updated.', complaint }); } catch (error) { next(error); } }
export async function deleteComplaint(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Complaint not found.' }); const complaint = await Report.findById(req.params.id); if (!complaint) return res.status(404).json({ success: false, message: 'Complaint not found.' }); await log(req.user, 'complaint_deleted', 'report', complaint._id, complaint.title, 'Complaint deleted.'); await complaint.deleteOne(); res.json({ success: true, message: 'Complaint deleted.' }); } catch (error) { next(error); } }

export async function listEmergencies(req, res, next) { try { const filter = {}; if (emergencyStatuses.includes(req.query.status)) filter.status = req.query.status; if (req.query.type) filter.type = req.query.type; if (req.query.search?.trim()) { const exp = new RegExp(escapeRegex(req.query.search), 'i'); filter.$or = [{ title: exp }, { citizenName: exp }, { 'location.address': exp }]; } const page = pageOf(req.query.page); const limit = limitOf(req.query.limit); const [emergencies, total] = await Promise.all([Emergency.find(filter).populate('citizen', 'name email phone photoURL').populate('assignedDepartment', 'name').populate('assignedOfficer', 'name email photoURL').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Emergency.countDocuments(filter)]); res.json({ success: true, emergencies, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function getEmergencyDetail(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Emergency not found.' }); const emergency = await Emergency.findById(req.params.id).populate('citizen', 'name email phone photoURL').populate('assignedDepartment', 'name').populate('assignedOfficer', 'name email phone photoURL').lean(); if (!emergency) return res.status(404).json({ success: false, message: 'Emergency not found.' }); res.json({ success: true, emergency }); } catch (error) { next(error); } }
export async function updateEmergency(req, res, next) { try { if (!objectId(req.params.id)) return res.status(404).json({ success: false, message: 'Emergency not found.' }); const emergency = await Emergency.findById(req.params.id); if (!emergency) return res.status(404).json({ success: false, message: 'Emergency not found.' }); const { status, departmentId, officerId, fieldWorkerId, notes } = req.body; if (status !== undefined && !emergencyStatuses.includes(status)) return res.status(400).json({ success: false, message: 'Invalid emergency status.' }); if (departmentId !== undefined) { const department = departmentId ? await Department.findById(departmentId) : null; if (departmentId && (!department || !['emergency', 'hybrid'].includes(department.scope) || !department.emergencyTypes.includes(emergency.type))) return res.status(400).json({ success: false, message: 'Choose an emergency-enabled department configured for this emergency type.' }); emergency.assignedDepartment = department?._id || null; } else if (!emergency.assignedDepartment) { const department = await Department.findOne({ status: 'active', scope: { $in: ['emergency', 'hybrid'] }, emergencyTypes: emergency.type }); if (department) emergency.assignedDepartment = department._id; } const assignmentDepartment = emergency.assignedDepartment; if (officerId !== undefined) { const officer = officerId ? await User.findOne({ _id: officerId, department: assignmentDepartment, status: 'active', role: { $in: ['emergency_department_officer', 'emergency_officer'] } }) : null; if (officerId && !officer) return res.status(400).json({ success: false, message: 'Officer is not active in the assigned emergency department.' }); emergency.assignedOfficer = officer?._id || null; } if (fieldWorkerId !== undefined) { const worker = fieldWorkerId ? await User.findOne({ _id: fieldWorkerId, department: assignmentDepartment, status: 'active', role: 'emergency_field_worker' }) : null; if (fieldWorkerId && !worker) return res.status(400).json({ success: false, message: 'Field worker is not active in the assigned emergency department.' }); emergency.assignedFieldWorker = worker?._id || null; } if (status) { if (status === 'resolved' && !emergency.resolvedAt) { emergency.resolvedAt = new Date(); } emergency.status = status; } if (notes !== undefined) emergency.notes = String(notes).slice(0, 1000); emergency.activity.push({ action: 'Emergency updated by administrator', actorRole: 'admin', note: String(notes || '').slice(0, 500) }); await emergency.save(); await log(req.user, 'emergency_updated', 'emergency', emergency._id, emergency.title, 'Emergency updated.'); res.json({ success: true, message: 'Emergency updated.', emergency }); } catch (error) { next(error); } }

export async function listActivityLogs(req, res, next) { try { const page = pageOf(req.query.page); const limit = limitOf(req.query.limit); const filter = req.query.action?.trim() ? { action: req.query.action.trim() } : {}; const [logs, total] = await Promise.all([ActivityLog.find(filter).populate('admin', 'name email photoURL').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), ActivityLog.countDocuments(filter)]); res.json({ success: true, logs, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
const safeSettings = { general: { portalName: 'CivicSync', timezone: 'Asia/Dhaka' }, notifications: { emailDigest: true, criticalAlerts: true }, security: { sessionNotice: true, activityRetentionDays: 365 } };
export async function getSettings(req, res, next) { try { const record = await SystemSetting.findOne({ key: 'admin_portal' }).lean(); res.json({ success: true, settings: { ...safeSettings, ...(record?.value || {}) } }); } catch (error) { next(error); } }
export async function updateSettings(req, res, next) { try { const value = { general: { ...safeSettings.general, ...(req.body.general || {}) }, notifications: { ...safeSettings.notifications, ...(req.body.notifications || {}) }, security: { ...safeSettings.security, ...(req.body.security || {}) } }; await SystemSetting.findOneAndUpdate({ key: 'admin_portal' }, { value, updatedBy: req.user._id }, { upsert: true, new: true, setDefaultsOnInsert: true }); await log(req.user, 'settings_changed', 'system', req.user._id, 'Admin portal settings', 'System settings updated.'); res.json({ success: true, message: 'Settings saved.', settings: value }); } catch (error) { next(error); } }
export async function exportReport(req, res, next) { try { const type = ['complaints', 'emergencies', 'users', 'departments'].includes(req.query.type) ? req.query.type : 'complaints'; let headers; let rows; if (type === 'emergencies') { headers = ['Emergency ID', 'Citizen', 'Type', 'Status', 'Department', 'Created']; rows = (await Emergency.find().populate('assignedDepartment', 'name').sort({ createdAt: -1 }).lean()).map((item) => [item._id, item.citizenName, item.type, item.status, item.assignedDepartment?.name || '', item.createdAt]); } else if (type === 'users') { headers = ['User ID', 'Name', 'Email', 'Role', 'Status', 'Department', 'Joined']; rows = (await User.find().sort({ createdAt: -1 }).lean()).map((item) => [item._id, item.name, item.email, item.role, item.status, item.departmentName, item.createdAt]); } else if (type === 'departments') { headers = ['Department', 'Type', 'Status', 'Email', 'Created']; rows = (await Department.find().sort({ name: 1 }).lean()).map((item) => [item.name, item.type, item.status, item.email, item.createdAt]); } else { headers = ['Complaint ID', 'Title', 'Citizen', 'Department', 'Priority', 'Status', 'Created']; rows = (await reportQuery(reportFilter(req.query)).sort({ createdAt: -1 }).lean()).map((item) => [item._id, item.title, item.createdBy?.name || '', item.departmentName, item.priority, item.status, item.createdAt]); } const csv = [headers, ...rows].map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); res.setHeader('Content-Type', 'text/csv; charset=utf-8'); res.setHeader('Content-Disposition', `attachment; filename="civicsync-${type}-${new Date().toISOString().slice(0, 10)}.csv"`); res.send(csv); } catch (error) { next(error); } }
