import mongoose from 'mongoose';
import fs from 'node:fs/promises';
import path from 'node:path';
import CommunityPost from '../models/CommunityPost.js';
import CommunityComment from '../models/CommunityComment.js';
import CommunityInteraction from '../models/CommunityInteraction.js';
import CommunityModerationReport from '../models/CommunityModerationReport.js';
import CommunityDraft from '../models/CommunityDraft.js';
import Notification from '../models/Notification.js';
import ActivityLog from '../models/ActivityLog.js';
import { communityUploadDir } from '../middleware/uploadMiddleware.js';
import { emitEmergencyEvent } from '../realtime/emergencyRealtime.js';
import { canDeleteComment, canEditComment, descendantIds, threadComments } from '../services/communityThread.js';

const categories = ['general', 'local_issue', 'safety', 'emergency_awareness', 'community_help', 'lost_found', 'event', 'announcement', 'discussion'];
const visibility = ['public', 'community', 'followers']; const reactions = ['like', 'helpful', 'support', 'concern', 'celebrate'];
const id = (value) => mongoose.Types.ObjectId.isValid(value); const clean = (value, max = 3000) => String(value || '').trim().slice(0, max);
const hashtagList = (content) => [...new Set((content.match(/(^|\s)#([\p{L}\p{N}_-]{2,40})/gu) || []).map((item) => item.trim().slice(1).toLowerCase()))].slice(0, 12);
async function blockedBy(userId) { const rows = await CommunityInteraction.find({ actor: userId, targetType: 'user', kind: 'block' }).select('target').lean(); return rows.map((row) => row.target); }
async function visibleFilter(user) { const blocked = await blockedBy(user._id); const follows = await CommunityInteraction.find({ actor: user._id, targetType: 'user', kind: 'follow' }).select('target').lean(); return { status: 'published', author: { $nin: blocked }, $or: [{ visibility: { $in: ['public', 'community'] } }, { author: user._id }, { visibility: 'followers', author: { $in: follows.map((row) => row.target) } }] }; }
function media(files = []) { return files.map((file) => ({ filename: file.filename, originalName: file.originalname, mimeType: file.mimetype, size: file.size, mediaType: file.mimetype.startsWith('video/') ? 'video' : 'image' })); }
async function removeMedia(items = []) { await Promise.all(items.map((item) => fs.unlink(path.join(communityUploadDir, path.basename(item.filename))).catch(() => {}))); }
async function notify(recipient, post, message) { if (String(recipient) === String(post.author)) return; await Notification.create({ recipient, relatedType: 'community', relatedId: post._id, type: 'community', message }); emitEmergencyEvent('COMMUNITY_NOTIFICATION_CREATED', { postId: post._id }, { userIds: [recipient] }); }
function serialize(post, viewer, reaction = null, saved = false) { const item = post.toObject ? post.toObject() : post; return { ...item, viewerReaction: reaction?.kind || null, saved, canManage: String(item.author?._id || item.author) === String(viewer._id), media: (item.media || []).map((file) => ({ ...file, url: `/api/community/posts/${item._id}/media/${encodeURIComponent(file.filename)}` })) }; }
async function enrich(posts, user) { const ids = posts.map((post) => post._id); const rows = await CommunityInteraction.find({ actor: user._id, target: { $in: ids }, kind: { $in: [...reactions, 'save'] } }).lean(); return posts.map((post) => serialize(post, user, rows.find((row) => String(row.target) === String(post._id) && reactions.includes(row.kind)), rows.some((row) => String(row.target) === String(post._id) && row.kind === 'save'))); }
async function ownedPost(postId, user) { if (!id(postId)) return null; const post = await CommunityPost.findById(postId).populate('author', 'name photoURL'); return post && String(post.author._id || post.author) === String(user._id) ? post : null; }

export async function listPosts(req, res, next) { try { const limit = Math.min(Math.max(Number(req.query.limit) || 15, 1), 40); const page = Math.max(Number(req.query.page) || 1, 1); const filter = await visibleFilter(req.user); if (categories.includes(req.query.category)) filter.category = req.query.category; if (req.query.hashtag) filter.hashtags = clean(req.query.hashtag, 40).replace(/^#/, '').toLowerCase(); if (req.query.mode === 'following') { const follows = await CommunityInteraction.find({ actor: req.user._id, targetType: 'user', kind: 'follow' }).select('target').lean(); filter.author = { $in: follows.map((row) => row.target) }; } if (req.query.search) { const term = new RegExp(clean(req.query.search, 100).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); filter.$and = [{ $or: [{ content: term }, { hashtags: term }] }]; } const [rows, total] = await Promise.all([CommunityPost.find(filter).populate('author', 'name photoURL').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), CommunityPost.countDocuments(filter)]); res.json({ success: true, posts: await enrich(rows, req.user), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } }
export async function getPost(req, res, next) { try { if (!id(req.params.id)) return res.status(404).json({ success: false, message: 'Post not found.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter).populate('author', 'name photoURL'); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); res.json({ success: true, post: (await enrich([post], req.user))[0] }); } catch (error) { next(error); } }
export async function createPost(req, res, next) { try { const content = clean(req.body.content); if (!content && !req.files?.length) { await removeMedia(media(req.files)); return res.status(400).json({ success: false, message: 'Write a post or attach media.' }); } const category = categories.includes(req.body.category) ? req.body.category : 'general'; const post = await CommunityPost.create({ author: req.user._id, content, media: media(req.files), category, visibility: visibility.includes(req.body.visibility) ? req.body.visibility : 'community', location: { area: clean(req.body.area, 100), label: clean(req.body.locationLabel, 140) }, hashtags: hashtagList(content) }); await post.populate('author', 'name photoURL'); await ActivityLog.create({ admin: req.user._id, actorRole: req.user.role, action: 'community_post_created', targetType: 'community_post', targetId: post._id, targetName: content.slice(0, 80) || 'Media post', result: 'success' }); emitEmergencyEvent('COMMUNITY_POST_CREATED', { postId: post._id }, { roles: ['citizen'] }); res.status(201).json({ success: true, post: serialize(post, req.user) }); } catch (error) { await removeMedia(media(req.files)); next(error); } }
export async function updatePost(req, res, next) { try { const post = await ownedPost(req.params.id, req.user); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); if (req.body.content !== undefined) { post.content = clean(req.body.content); post.hashtags = hashtagList(post.content); } if (categories.includes(req.body.category)) post.category = req.body.category; if (visibility.includes(req.body.visibility)) post.visibility = req.body.visibility; if (req.body.area !== undefined) post.location.area = clean(req.body.area, 100); if (req.body.locationLabel !== undefined) post.location.label = clean(req.body.locationLabel, 140); if (!post.content && !post.media.length && !req.files?.length) return res.status(400).json({ success: false, message: 'A post needs text or media.' }); post.media.push(...media(req.files)); await post.save(); emitEmergencyEvent('COMMUNITY_POST_UPDATED', { postId: post._id }, { userIds: [req.user._id] }); res.json({ success: true, post: (await enrich([post], req.user))[0] }); } catch (error) { await removeMedia(media(req.files)); next(error); } }
export async function deletePost(req, res, next) { try { const post = await ownedPost(req.params.id, req.user); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); post.status = 'removed'; await post.save(); await CommunityComment.updateMany({ post: post._id }, { status: 'removed' }); await ActivityLog.create({ admin: req.user._id, actorRole: req.user.role, action: 'community_post_deleted', targetType: 'community_post', targetId: post._id, targetName: post.content.slice(0, 80), result: 'success' }); emitEmergencyEvent('COMMUNITY_POST_DELETED', { postId: post._id }, { roles: ['citizen'] }); res.json({ success: true, message: 'Post removed.' }); } catch (error) { next(error); } }
export async function react(req, res, next) { try { if (!reactions.includes(req.body.type) || !id(req.params.id)) return res.status(400).json({ success: false, message: 'Choose a valid reaction.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); const existing = await CommunityInteraction.findOne({ actor: req.user._id, targetType: 'post', target: post._id, kind: req.body.type }); await CommunityInteraction.deleteMany({ actor: req.user._id, targetType: 'post', target: post._id, kind: { $in: reactions } }); if (!existing) await CommunityInteraction.create({ actor: req.user._id, targetType: 'post', target: post._id, kind: req.body.type }); post.reactionCount = await CommunityInteraction.countDocuments({ targetType: 'post', target: post._id, kind: { $in: reactions } }); await post.save(); if (!existing) await notify(post.author, post, `${req.user.name} reacted to your community post.`); emitEmergencyEvent('COMMUNITY_REACTION_UPDATED', { postId: post._id, reactionCount: post.reactionCount }, { userIds: [post.author] }); res.json({ success: true, reaction: existing ? null : req.body.type, reactionCount: post.reactionCount }); } catch (error) { next(error); } }
export async function toggleSave(req, res, next) { try { const post = await CommunityPost.findById(req.params.id); if (!post || post.status !== 'published') return res.status(404).json({ success: false, message: 'Post not found.' }); const found = await CommunityInteraction.findOne({ actor: req.user._id, targetType: 'post', target: post._id, kind: 'save' }); if (found) await found.deleteOne(); else await CommunityInteraction.create({ actor: req.user._id, targetType: 'post', target: post._id, kind: 'save' }); res.json({ success: true, saved: !found }); } catch (error) { next(error); } }
export async function listSaved(req, res, next) { try { const rows = await CommunityInteraction.find({ actor: req.user._id, targetType: 'post', kind: 'save' }).sort({ createdAt: -1 }).limit(100).lean(); const posts = await CommunityPost.find({ _id: { $in: rows.map((row) => row.target) }, status: 'published' }).populate('author', 'name photoURL'); res.json({ success: true, posts: await enrich(posts, req.user) }); } catch (error) { next(error); } }
export async function listComments(req, res, next) { try { if (!id(req.params.id)) return res.status(404).json({ success: false, message: 'Post not found.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter).select('author'); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); const rows = await CommunityComment.find({ post: post._id, status: 'published' }).populate('author', 'name photoURL').sort({ createdAt: 1 }).limit(200).lean(); const comments = threadComments(rows).map((comment) => ({ ...comment, canEdit: canEditComment(req.user, comment), canManage: canEditComment(req.user, comment) || canDeleteComment(req.user, comment, post) })); res.json({ success: true, comments, total: comments.length }); } catch (error) { next(error); } }
export async function createComment(req, res, next) { try { const content = clean(req.body.content, 1500); if (!content || !id(req.params.id)) return res.status(400).json({ success: false, message: 'Write a comment first.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); const parent = id(req.body.parent) ? await CommunityComment.findOne({ _id: req.body.parent, post: post._id, status: 'published' }) : null; if (req.body.parent && !parent) return res.status(400).json({ success: false, message: 'Reply target is unavailable.' }); const comment = await CommunityComment.create({ post: post._id, author: req.user._id, parent: parent?._id || null, content }); post.commentCount += 1; await post.save(); await comment.populate('author', 'name photoURL'); await notify(post.author, post, `${req.user.name} ${parent ? 'replied to a comment on' : 'commented on'} your community post.`); emitEmergencyEvent('COMMUNITY_COMMENT_CREATED', { postId: post._id, commentId: comment._id }, { userIds: [post.author] }); res.status(201).json({ success: true, comment: { ...comment.toObject(), depth: parent ? 1 : 0, replyCount: 0, canEdit: true, canManage: true }, commentCount: post.commentCount }); } catch (error) { next(error); } }

export async function updateComment(req, res, next) { try { const content = clean(req.body.content, 1500); if (!id(req.params.id) || !id(req.params.commentId)) return res.status(404).json({ success: false, message: 'Comment not found.' }); if (!content) return res.status(400).json({ success: false, message: 'Write something before saving your edit.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter).select('author'); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); const comment = await CommunityComment.findOne({ _id: req.params.commentId, post: post._id, status: 'published' }); if (!comment) return res.status(404).json({ success: false, message: 'Comment not found.' }); if (!canEditComment(req.user, comment)) return res.status(403).json({ success: false, message: 'You can only edit your own comment.' }); comment.content = content; comment.editedAt = new Date(); await comment.save(); await comment.populate('author', 'name photoURL'); await ActivityLog.create({ admin: req.user._id, actorRole: req.user.role, action: 'community_comment_updated', targetType: 'community_comment', targetId: comment._id, targetName: content.slice(0, 80), result: 'success' }); emitEmergencyEvent('COMMUNITY_COMMENT_UPDATED', { postId: post._id, commentId: comment._id }, { userIds: [post.author] }); res.json({ success: true, comment: { ...comment.toObject(), canEdit: true, canManage: true } }); } catch (error) { next(error); } }

export async function deleteComment(req, res, next) { try { if (!id(req.params.id) || !id(req.params.commentId)) return res.status(404).json({ success: false, message: 'Comment not found.' }); const filter = await visibleFilter(req.user); filter._id = req.params.id; const post = await CommunityPost.findOne(filter).select('author'); if (!post) return res.status(404).json({ success: false, message: 'Post not found.' }); const rows = await CommunityComment.find({ post: post._id, status: 'published' }).select('_id author parent status').lean(); const comment = rows.find((row) => String(row._id) === String(req.params.commentId)); if (!comment) return res.status(404).json({ success: false, message: 'Comment not found.' }); if (!canDeleteComment(req.user, comment, post)) return res.status(403).json({ success: false, message: 'You cannot delete this comment.' }); const removedIds = [String(comment._id), ...descendantIds(rows, comment._id)]; await CommunityComment.deleteMany({ _id: { $in: removedIds } }); post.commentCount = await CommunityComment.countDocuments({ post: post._id, status: 'published' }); await post.save(); await ActivityLog.create({ admin: req.user._id, actorRole: req.user.role, action: 'community_comment_deleted', targetType: 'community_comment', targetId: comment._id, targetName: 'Comment removed', result: 'success' }); emitEmergencyEvent('COMMUNITY_COMMENT_DELETED', { postId: post._id, commentId: comment._id, removedIds }, { userIds: [post.author] }); res.json({ success: true, removedIds, commentCount: post.commentCount }); } catch (error) { next(error); } }
export async function toggleFollow(req, res, next) { try { if (!id(req.params.id) || String(req.params.id) === String(req.user._id)) return res.status(400).json({ success: false, message: 'You cannot follow this user.' }); const target = await mongoose.model('User').findById(req.params.id).select('_id name'); if (!target) return res.status(404).json({ success: false, message: 'User not found.' }); const blocked = await CommunityInteraction.exists({ actor: req.user._id, targetType: 'user', target: target._id, kind: 'block' }); if (blocked) return res.status(403).json({ success: false, message: 'Unblock this user before following them.' }); const found = await CommunityInteraction.findOne({ actor: req.user._id, targetType: 'user', target: target._id, kind: 'follow' }); if (found) await found.deleteOne(); else { await CommunityInteraction.create({ actor: req.user._id, targetType: 'user', target: target._id, kind: 'follow' }); await Notification.create({ recipient: target._id, relatedType: 'community', relatedId: target._id, type: 'community', message: `${req.user.name} started following you.` }); } res.json({ success: true, following: !found }); } catch (error) { next(error); } }
export async function toggleBlock(req, res, next) { try { if (!id(req.params.id) || String(req.params.id) === String(req.user._id)) return res.status(400).json({ success: false, message: 'You cannot block this user.' }); const found = await CommunityInteraction.findOne({ actor: req.user._id, targetType: 'user', target: req.params.id, kind: 'block' }); if (found) await found.deleteOne(); else { await CommunityInteraction.create({ actor: req.user._id, targetType: 'user', target: req.params.id, kind: 'block' }); await CommunityInteraction.deleteMany({ actor: req.user._id, targetType: 'user', target: req.params.id, kind: 'follow' }); } res.json({ success: true, blocked: !found }); } catch (error) { next(error); } }
export async function submitModerationReport(req, res, next) { try { if (!['post', 'comment', 'user'].includes(req.body.targetType) || !id(req.body.target) || !req.body.reason) return res.status(400).json({ success: false, message: 'Choose valid content and a report reason.' }); const record = await CommunityModerationReport.create({ reporter: req.user._id, targetType: req.body.targetType, target: req.body.target, reason: req.body.reason, description: clean(req.body.description, 800) }); await ActivityLog.create({ admin: req.user._id, actorRole: req.user.role, action: 'community_content_reported', targetType: `community_${req.body.targetType}`, targetId: req.body.target, targetName: req.body.reason, result: 'success' }); emitEmergencyEvent('COMMUNITY_MODERATION_UPDATED', { reportId: record._id }, { roles: ['admin'] }); res.status(201).json({ success: true, message: 'Thank you. Your report was sent for review.' }); } catch (error) { if (error?.code === 11000) return res.status(409).json({ success: false, message: 'You already reported this content.' }); next(error); } }
export async function getDraft(req, res, next) { try { res.json({ success: true, draft: await CommunityDraft.findOne({ author: req.user._id }).lean() }); } catch (error) { next(error); } }
export async function saveDraft(req, res, next) { try { const draft = await CommunityDraft.findOneAndUpdate({ author: req.user._id }, { content: clean(req.body.content), category: categories.includes(req.body.category) ? req.body.category : 'general', visibility: visibility.includes(req.body.visibility) ? req.body.visibility : 'community', location: { area: clean(req.body.area, 100), label: clean(req.body.locationLabel, 140) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); res.json({ success: true, draft }); } catch (error) { next(error); } }
export async function deleteDraft(req, res, next) { try { await CommunityDraft.deleteOne({ author: req.user._id }); res.status(204).end(); } catch (error) { next(error); } }
export async function getMedia(req, res, next) { try { const post = await CommunityPost.findById(req.params.id); if (!post || !post.media.some((file) => file.filename === path.basename(req.params.filename))) return res.status(404).json({ success: false, message: 'Media not found.' }); const filter = await visibleFilter(req.user); filter._id = post._id; if (!await CommunityPost.exists(filter)) return res.status(404).json({ success: false, message: 'Media not found.' }); res.sendFile(path.join(communityUploadDir, path.basename(req.params.filename))); } catch (error) { next(error); } }
